useFixture(default)

def test():
	from Modules import commonBits
	java_recorded_version = '1.6.0_22'

	if window('Protocol Buffer Editor'):
		select('File_Txt', commonBits.sampleDir() + 'protoStoreSales7.bin')
		click('Edit1')
		select_menu('Window>>Show Child Record')
		select('LineTreeChild.FileDisplay_JTbl', 'cell:Tree,0(null)')
		assert_p('LineFrameTree.FileDisplay_JTbl', 'Content', '[[store, 1, , INT32, 20, 20], [name, 2, , STRING, Store: 20, Store: 20]]')
		select('LineTreeChild.FileDisplay_JTbl', 'cell:Tree,0(null)')
		click('Find1')
##		click('MetalInternalFrameTitlePane', 184, 10)
		select('Find.Search For_Txt', '57')
		click('Find >>')
		assert_p('LineFrameTree.FileDisplay_JTbl', 'Content', '[[department, 1, , INT32, 957, 957], [name, 2, , STRING, Department: 957, Department: 957]]')
		click('Find >>')
		click('Find >>')
		assert_p('LineFrameTree.FileDisplay_JTbl', 'Content', '[[department, 1, , INT32, 957, 957], [name, 2, , STRING, Department: 957, Department: 957]]')
		click('Find >>')
		click('Find >>')
		assert_p('LineFrameTree.FileDisplay_JTbl', 'Content', '[[quantity, 1, , INT32, 3, 3], [price, 2, , INT64, 57000, 57000], [count, 3, , INT32, 3, 3]]')
		click('Find >>')
		assert_p('LineFrameTree.FileDisplay_JTbl', 'Content', '[[department, 1, , INT32, 957, 957], [name, 2, , STRING, Department: 957, Department: 957]]')
		click('Find >>')
		click('Find >>')
		assert_p('LineFrameTree.FileDisplay_JTbl', 'Content', '[[keycode, 1, , INT32, 62664576, 62664576], [quantity, 2, , INT32, 1, 1]]')
		click('Find >>')
		click('Find >>')
		click('Find >>')
		click('Find >>')
		assert_p('LineFrameTree.FileDisplay_JTbl', 'Content', '[[quantity, 1, , INT32, -1, -1], [price, 2, , INT64, 1570, 1570], [count, 3, , INT32, 3, 3]]')
		click('Find >>')
		assert_p('LineFrameTree.FileDisplay_JTbl', 'Content', '[[department, 1, , INT32, 957, 957], [name, 2, , STRING, Department: 957, Department: 957]]')
		select('Find.Direction_Txt', 'Backward')
		click('Find >>')
		assert_p('LineFrameTree.FileDisplay_JTbl', 'Content', '[[quantity, 1, , INT32, -1, -1], [price, 2, , INT64, 1570, 1570], [count, 3, , INT32, 3, 3]]')
	close()
