// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Ams_Location.proto

package net.sf.RecordEditor.ProtoBuf.re.Test.ams;

public final class AmsLocation {
  private AmsLocation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LocationsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string Brand_Id = 1;
    boolean hasBrandId();
    String getBrandId();
    
    // required string Loc_Nbr = 2;
    boolean hasLocNbr();
    String getLocNbr();
    
    // required string Loc_Type = 3;
    boolean hasLocType();
    String getLocType();
    
    // required string Loc_Name = 4;
    boolean hasLocName();
    String getLocName();
    
    // required string Loc_Addr_Ln1 = 5;
    boolean hasLocAddrLn1();
    String getLocAddrLn1();
    
    // required string Loc_Addr_Ln2 = 6;
    boolean hasLocAddrLn2();
    String getLocAddrLn2();
    
    // required string Loc_Addr_Ln3 = 7;
    boolean hasLocAddrLn3();
    String getLocAddrLn3();
    
    // required string Loc_Postcode = 8;
    boolean hasLocPostcode();
    String getLocPostcode();
    
    // required string Loc_State = 9;
    boolean hasLocState();
    String getLocState();
    
    // required string Loc_Actv_Ind = 10;
    boolean hasLocActvInd();
    String getLocActvInd();
  }
  public static final class Locations extends
      com.google.protobuf.GeneratedMessage
      implements LocationsOrBuilder {
    // Use Locations.newBuilder() to construct.
    private Locations(Builder builder) {
      super(builder);
    }
    private Locations(boolean noInit) {}
    
    private static final Locations defaultInstance;
    public static Locations getDefaultInstance() {
      return defaultInstance;
    }
    
    public Locations getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_ams_Locations_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_ams_Locations_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string Brand_Id = 1;
    public static final int BRAND_ID_FIELD_NUMBER = 1;
    private java.lang.Object brandId_;
    public boolean hasBrandId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getBrandId() {
      java.lang.Object ref = brandId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          brandId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBrandIdBytes() {
      java.lang.Object ref = brandId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        brandId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string Loc_Nbr = 2;
    public static final int LOC_NBR_FIELD_NUMBER = 2;
    private java.lang.Object locNbr_;
    public boolean hasLocNbr() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getLocNbr() {
      java.lang.Object ref = locNbr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          locNbr_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLocNbrBytes() {
      java.lang.Object ref = locNbr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        locNbr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string Loc_Type = 3;
    public static final int LOC_TYPE_FIELD_NUMBER = 3;
    private java.lang.Object locType_;
    public boolean hasLocType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getLocType() {
      java.lang.Object ref = locType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          locType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLocTypeBytes() {
      java.lang.Object ref = locType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        locType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string Loc_Name = 4;
    public static final int LOC_NAME_FIELD_NUMBER = 4;
    private java.lang.Object locName_;
    public boolean hasLocName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getLocName() {
      java.lang.Object ref = locName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          locName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLocNameBytes() {
      java.lang.Object ref = locName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        locName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string Loc_Addr_Ln1 = 5;
    public static final int LOC_ADDR_LN1_FIELD_NUMBER = 5;
    private java.lang.Object locAddrLn1_;
    public boolean hasLocAddrLn1() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getLocAddrLn1() {
      java.lang.Object ref = locAddrLn1_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          locAddrLn1_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLocAddrLn1Bytes() {
      java.lang.Object ref = locAddrLn1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        locAddrLn1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string Loc_Addr_Ln2 = 6;
    public static final int LOC_ADDR_LN2_FIELD_NUMBER = 6;
    private java.lang.Object locAddrLn2_;
    public boolean hasLocAddrLn2() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getLocAddrLn2() {
      java.lang.Object ref = locAddrLn2_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          locAddrLn2_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLocAddrLn2Bytes() {
      java.lang.Object ref = locAddrLn2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        locAddrLn2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string Loc_Addr_Ln3 = 7;
    public static final int LOC_ADDR_LN3_FIELD_NUMBER = 7;
    private java.lang.Object locAddrLn3_;
    public boolean hasLocAddrLn3() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getLocAddrLn3() {
      java.lang.Object ref = locAddrLn3_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          locAddrLn3_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLocAddrLn3Bytes() {
      java.lang.Object ref = locAddrLn3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        locAddrLn3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string Loc_Postcode = 8;
    public static final int LOC_POSTCODE_FIELD_NUMBER = 8;
    private java.lang.Object locPostcode_;
    public boolean hasLocPostcode() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getLocPostcode() {
      java.lang.Object ref = locPostcode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          locPostcode_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLocPostcodeBytes() {
      java.lang.Object ref = locPostcode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        locPostcode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string Loc_State = 9;
    public static final int LOC_STATE_FIELD_NUMBER = 9;
    private java.lang.Object locState_;
    public boolean hasLocState() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getLocState() {
      java.lang.Object ref = locState_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          locState_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLocStateBytes() {
      java.lang.Object ref = locState_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        locState_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string Loc_Actv_Ind = 10;
    public static final int LOC_ACTV_IND_FIELD_NUMBER = 10;
    private java.lang.Object locActvInd_;
    public boolean hasLocActvInd() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getLocActvInd() {
      java.lang.Object ref = locActvInd_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          locActvInd_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLocActvIndBytes() {
      java.lang.Object ref = locActvInd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        locActvInd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      brandId_ = "";
      locNbr_ = "";
      locType_ = "";
      locName_ = "";
      locAddrLn1_ = "";
      locAddrLn2_ = "";
      locAddrLn3_ = "";
      locPostcode_ = "";
      locState_ = "";
      locActvInd_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasBrandId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocNbr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocAddrLn1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocAddrLn2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocAddrLn3()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocPostcode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocActvInd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getBrandIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLocNbrBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLocTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getLocNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getLocAddrLn1Bytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getLocAddrLn2Bytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getLocAddrLn3Bytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getLocPostcodeBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getLocStateBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getLocActvIndBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBrandIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLocNbrBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLocTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getLocNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getLocAddrLn1Bytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getLocAddrLn2Bytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getLocAddrLn3Bytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getLocPostcodeBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getLocStateBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getLocActvIndBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.LocationsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_ams_Locations_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_ams_Locations_fieldAccessorTable;
      }
      
      // Construct using net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        brandId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        locNbr_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        locType_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        locName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        locAddrLn1_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        locAddrLn2_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        locAddrLn3_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        locPostcode_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        locState_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        locActvInd_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations.getDescriptor();
      }
      
      public net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations getDefaultInstanceForType() {
        return net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations.getDefaultInstance();
      }
      
      public net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations build() {
        net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations buildPartial() {
        net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations result = new net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.brandId_ = brandId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.locNbr_ = locNbr_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.locType_ = locType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.locName_ = locName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.locAddrLn1_ = locAddrLn1_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.locAddrLn2_ = locAddrLn2_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.locAddrLn3_ = locAddrLn3_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.locPostcode_ = locPostcode_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.locState_ = locState_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.locActvInd_ = locActvInd_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations) {
          return mergeFrom((net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations other) {
        if (other == net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations.getDefaultInstance()) return this;
        if (other.hasBrandId()) {
          setBrandId(other.getBrandId());
        }
        if (other.hasLocNbr()) {
          setLocNbr(other.getLocNbr());
        }
        if (other.hasLocType()) {
          setLocType(other.getLocType());
        }
        if (other.hasLocName()) {
          setLocName(other.getLocName());
        }
        if (other.hasLocAddrLn1()) {
          setLocAddrLn1(other.getLocAddrLn1());
        }
        if (other.hasLocAddrLn2()) {
          setLocAddrLn2(other.getLocAddrLn2());
        }
        if (other.hasLocAddrLn3()) {
          setLocAddrLn3(other.getLocAddrLn3());
        }
        if (other.hasLocPostcode()) {
          setLocPostcode(other.getLocPostcode());
        }
        if (other.hasLocState()) {
          setLocState(other.getLocState());
        }
        if (other.hasLocActvInd()) {
          setLocActvInd(other.getLocActvInd());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasBrandId()) {
          
          return false;
        }
        if (!hasLocNbr()) {
          
          return false;
        }
        if (!hasLocType()) {
          
          return false;
        }
        if (!hasLocName()) {
          
          return false;
        }
        if (!hasLocAddrLn1()) {
          
          return false;
        }
        if (!hasLocAddrLn2()) {
          
          return false;
        }
        if (!hasLocAddrLn3()) {
          
          return false;
        }
        if (!hasLocPostcode()) {
          
          return false;
        }
        if (!hasLocState()) {
          
          return false;
        }
        if (!hasLocActvInd()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              brandId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              locNbr_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              locType_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              locName_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              locAddrLn1_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              locAddrLn2_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              locAddrLn3_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              locPostcode_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              locState_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              locActvInd_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string Brand_Id = 1;
      private java.lang.Object brandId_ = "";
      public boolean hasBrandId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getBrandId() {
        java.lang.Object ref = brandId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          brandId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBrandId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        brandId_ = value;
        onChanged();
        return this;
      }
      public Builder clearBrandId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        brandId_ = getDefaultInstance().getBrandId();
        onChanged();
        return this;
      }
      void setBrandId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        brandId_ = value;
        onChanged();
      }
      
      // required string Loc_Nbr = 2;
      private java.lang.Object locNbr_ = "";
      public boolean hasLocNbr() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getLocNbr() {
        java.lang.Object ref = locNbr_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          locNbr_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLocNbr(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        locNbr_ = value;
        onChanged();
        return this;
      }
      public Builder clearLocNbr() {
        bitField0_ = (bitField0_ & ~0x00000002);
        locNbr_ = getDefaultInstance().getLocNbr();
        onChanged();
        return this;
      }
      void setLocNbr(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        locNbr_ = value;
        onChanged();
      }
      
      // required string Loc_Type = 3;
      private java.lang.Object locType_ = "";
      public boolean hasLocType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getLocType() {
        java.lang.Object ref = locType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          locType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLocType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        locType_ = value;
        onChanged();
        return this;
      }
      public Builder clearLocType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        locType_ = getDefaultInstance().getLocType();
        onChanged();
        return this;
      }
      void setLocType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        locType_ = value;
        onChanged();
      }
      
      // required string Loc_Name = 4;
      private java.lang.Object locName_ = "";
      public boolean hasLocName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getLocName() {
        java.lang.Object ref = locName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          locName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLocName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        locName_ = value;
        onChanged();
        return this;
      }
      public Builder clearLocName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        locName_ = getDefaultInstance().getLocName();
        onChanged();
        return this;
      }
      void setLocName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        locName_ = value;
        onChanged();
      }
      
      // required string Loc_Addr_Ln1 = 5;
      private java.lang.Object locAddrLn1_ = "";
      public boolean hasLocAddrLn1() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getLocAddrLn1() {
        java.lang.Object ref = locAddrLn1_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          locAddrLn1_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLocAddrLn1(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        locAddrLn1_ = value;
        onChanged();
        return this;
      }
      public Builder clearLocAddrLn1() {
        bitField0_ = (bitField0_ & ~0x00000010);
        locAddrLn1_ = getDefaultInstance().getLocAddrLn1();
        onChanged();
        return this;
      }
      void setLocAddrLn1(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        locAddrLn1_ = value;
        onChanged();
      }
      
      // required string Loc_Addr_Ln2 = 6;
      private java.lang.Object locAddrLn2_ = "";
      public boolean hasLocAddrLn2() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getLocAddrLn2() {
        java.lang.Object ref = locAddrLn2_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          locAddrLn2_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLocAddrLn2(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        locAddrLn2_ = value;
        onChanged();
        return this;
      }
      public Builder clearLocAddrLn2() {
        bitField0_ = (bitField0_ & ~0x00000020);
        locAddrLn2_ = getDefaultInstance().getLocAddrLn2();
        onChanged();
        return this;
      }
      void setLocAddrLn2(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        locAddrLn2_ = value;
        onChanged();
      }
      
      // required string Loc_Addr_Ln3 = 7;
      private java.lang.Object locAddrLn3_ = "";
      public boolean hasLocAddrLn3() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getLocAddrLn3() {
        java.lang.Object ref = locAddrLn3_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          locAddrLn3_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLocAddrLn3(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        locAddrLn3_ = value;
        onChanged();
        return this;
      }
      public Builder clearLocAddrLn3() {
        bitField0_ = (bitField0_ & ~0x00000040);
        locAddrLn3_ = getDefaultInstance().getLocAddrLn3();
        onChanged();
        return this;
      }
      void setLocAddrLn3(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        locAddrLn3_ = value;
        onChanged();
      }
      
      // required string Loc_Postcode = 8;
      private java.lang.Object locPostcode_ = "";
      public boolean hasLocPostcode() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getLocPostcode() {
        java.lang.Object ref = locPostcode_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          locPostcode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLocPostcode(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        locPostcode_ = value;
        onChanged();
        return this;
      }
      public Builder clearLocPostcode() {
        bitField0_ = (bitField0_ & ~0x00000080);
        locPostcode_ = getDefaultInstance().getLocPostcode();
        onChanged();
        return this;
      }
      void setLocPostcode(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        locPostcode_ = value;
        onChanged();
      }
      
      // required string Loc_State = 9;
      private java.lang.Object locState_ = "";
      public boolean hasLocState() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getLocState() {
        java.lang.Object ref = locState_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          locState_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLocState(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        locState_ = value;
        onChanged();
        return this;
      }
      public Builder clearLocState() {
        bitField0_ = (bitField0_ & ~0x00000100);
        locState_ = getDefaultInstance().getLocState();
        onChanged();
        return this;
      }
      void setLocState(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        locState_ = value;
        onChanged();
      }
      
      // required string Loc_Actv_Ind = 10;
      private java.lang.Object locActvInd_ = "";
      public boolean hasLocActvInd() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getLocActvInd() {
        java.lang.Object ref = locActvInd_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          locActvInd_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLocActvInd(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        locActvInd_ = value;
        onChanged();
        return this;
      }
      public Builder clearLocActvInd() {
        bitField0_ = (bitField0_ & ~0x00000200);
        locActvInd_ = getDefaultInstance().getLocActvInd();
        onChanged();
        return this;
      }
      void setLocActvInd(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        locActvInd_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:net.sf.RecordEditor.ProtoBuf.re.Test.ams.Locations)
    }
    
    static {
      defaultInstance = new Locations(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.sf.RecordEditor.ProtoBuf.re.Test.ams.Locations)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_ams_Locations_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_ams_Locations_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Ams_Location.proto\022(net.sf.RecordEdito" +
      "r.ProtoBuf.re.Test.ams\"\323\001\n\tLocations\022\020\n\010" +
      "Brand_Id\030\001 \002(\t\022\017\n\007Loc_Nbr\030\002 \002(\t\022\020\n\010Loc_T" +
      "ype\030\003 \002(\t\022\020\n\010Loc_Name\030\004 \002(\t\022\024\n\014Loc_Addr_" +
      "Ln1\030\005 \002(\t\022\024\n\014Loc_Addr_Ln2\030\006 \002(\t\022\024\n\014Loc_A" +
      "ddr_Ln3\030\007 \002(\t\022\024\n\014Loc_Postcode\030\010 \002(\t\022\021\n\tL" +
      "oc_State\030\t \002(\t\022\024\n\014Loc_Actv_Ind\030\n \002(\tB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_ams_Locations_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_ams_Locations_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_ams_Locations_descriptor,
              new java.lang.String[] { "BrandId", "LocNbr", "LocType", "LocName", "LocAddrLn1", "LocAddrLn2", "LocAddrLn3", "LocPostcode", "LocState", "LocActvInd", },
              net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations.class,
              net.sf.RecordEditor.ProtoBuf.re.Test.ams.AmsLocation.Locations.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
