// Generated by the protocol buffer compiler.  DO NOT EDIT!

package Sales3;

public final class StoreSales3 {
  private StoreSales3() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Product extends
      com.google.protobuf.GeneratedMessage {
    // Use Product.newBuilder() to construct.
    private Product() {}
    
    private static final Product defaultInstance = new Product();
    public static Product getDefaultInstance() {
      return defaultInstance;
    }
    
    public Product getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Sales3.StoreSales3.internal_static_Sales3_Product_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Sales3.StoreSales3.internal_static_Sales3_Product_fieldAccessorTable;
    }
    
    // required int32 keycode = 1;
    public static final int KEYCODE_FIELD_NUMBER = 1;
    private boolean hasKeycode;
    private int keycode_ = 0;
    public boolean hasKeycode() { return hasKeycode; }
    public int getKeycode() { return keycode_; }
    
    // required int32 saleDate = 2;
    public static final int SALEDATE_FIELD_NUMBER = 2;
    private boolean hasSaleDate;
    private int saleDate_ = 0;
    public boolean hasSaleDate() { return hasSaleDate; }
    public int getSaleDate() { return saleDate_; }
    
    // required int32 quantity = 3;
    public static final int QUANTITY_FIELD_NUMBER = 3;
    private boolean hasQuantity;
    private int quantity_ = 0;
    public boolean hasQuantity() { return hasQuantity; }
    public int getQuantity() { return quantity_; }
    
    // required int64 price = 4;
    public static final int PRICE_FIELD_NUMBER = 4;
    private boolean hasPrice;
    private long price_ = 0L;
    public boolean hasPrice() { return hasPrice; }
    public long getPrice() { return price_; }
    
    public final boolean isInitialized() {
      if (!hasKeycode) return false;
      if (!hasSaleDate) return false;
      if (!hasQuantity) return false;
      if (!hasPrice) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasKeycode()) {
        output.writeInt32(1, getKeycode());
      }
      if (hasSaleDate()) {
        output.writeInt32(2, getSaleDate());
      }
      if (hasQuantity()) {
        output.writeInt32(3, getQuantity());
      }
      if (hasPrice()) {
        output.writeInt64(4, getPrice());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKeycode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getKeycode());
      }
      if (hasSaleDate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getSaleDate());
      }
      if (hasQuantity()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getQuantity());
      }
      if (hasPrice()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, getPrice());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static Sales3.StoreSales3.Product parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Sales3.StoreSales3.Product parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Sales3.StoreSales3.Product parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Sales3.StoreSales3.Product parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Sales3.StoreSales3.Product parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Sales3.StoreSales3.Product parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Sales3.StoreSales3.Product parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static Sales3.StoreSales3.Product parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Sales3.StoreSales3.Product parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Sales3.StoreSales3.Product parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Sales3.StoreSales3.Product prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private Sales3.StoreSales3.Product result;
      
      // Construct using Sales3.StoreSales3.Product.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new Sales3.StoreSales3.Product();
        return builder;
      }
      
      protected Sales3.StoreSales3.Product internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new Sales3.StoreSales3.Product();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Sales3.StoreSales3.Product.getDescriptor();
      }
      
      public Sales3.StoreSales3.Product getDefaultInstanceForType() {
        return Sales3.StoreSales3.Product.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public Sales3.StoreSales3.Product build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private Sales3.StoreSales3.Product buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public Sales3.StoreSales3.Product buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        Sales3.StoreSales3.Product returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Sales3.StoreSales3.Product) {
          return mergeFrom((Sales3.StoreSales3.Product)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Sales3.StoreSales3.Product other) {
        if (other == Sales3.StoreSales3.Product.getDefaultInstance()) return this;
        if (other.hasKeycode()) {
          setKeycode(other.getKeycode());
        }
        if (other.hasSaleDate()) {
          setSaleDate(other.getSaleDate());
        }
        if (other.hasQuantity()) {
          setQuantity(other.getQuantity());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setKeycode(input.readInt32());
              break;
            }
            case 16: {
              setSaleDate(input.readInt32());
              break;
            }
            case 24: {
              setQuantity(input.readInt32());
              break;
            }
            case 32: {
              setPrice(input.readInt64());
              break;
            }
          }
        }
      }
      
      
      // required int32 keycode = 1;
      public boolean hasKeycode() {
        return result.hasKeycode();
      }
      public int getKeycode() {
        return result.getKeycode();
      }
      public Builder setKeycode(int value) {
        result.hasKeycode = true;
        result.keycode_ = value;
        return this;
      }
      public Builder clearKeycode() {
        result.hasKeycode = false;
        result.keycode_ = 0;
        return this;
      }
      
      // required int32 saleDate = 2;
      public boolean hasSaleDate() {
        return result.hasSaleDate();
      }
      public int getSaleDate() {
        return result.getSaleDate();
      }
      public Builder setSaleDate(int value) {
        result.hasSaleDate = true;
        result.saleDate_ = value;
        return this;
      }
      public Builder clearSaleDate() {
        result.hasSaleDate = false;
        result.saleDate_ = 0;
        return this;
      }
      
      // required int32 quantity = 3;
      public boolean hasQuantity() {
        return result.hasQuantity();
      }
      public int getQuantity() {
        return result.getQuantity();
      }
      public Builder setQuantity(int value) {
        result.hasQuantity = true;
        result.quantity_ = value;
        return this;
      }
      public Builder clearQuantity() {
        result.hasQuantity = false;
        result.quantity_ = 0;
        return this;
      }
      
      // required int64 price = 4;
      public boolean hasPrice() {
        return result.hasPrice();
      }
      public long getPrice() {
        return result.getPrice();
      }
      public Builder setPrice(long value) {
        result.hasPrice = true;
        result.price_ = value;
        return this;
      }
      public Builder clearPrice() {
        result.hasPrice = false;
        result.price_ = 0L;
        return this;
      }
    }
    
    static {
      Sales3.StoreSales3.getDescriptor();
    }
    
    static {
      Sales3.StoreSales3.internalForceInit();
    }
  }
  
  public static final class Order extends
      com.google.protobuf.GeneratedMessage {
    // Use Order.newBuilder() to construct.
    private Order() {}
    
    private static final Order defaultInstance = new Order();
    public static Order getDefaultInstance() {
      return defaultInstance;
    }
    
    public Order getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Sales3.StoreSales3.internal_static_Sales3_Order_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Sales3.StoreSales3.internal_static_Sales3_Order_fieldAccessorTable;
    }
    
    // required int32 keycode = 1;
    public static final int KEYCODE_FIELD_NUMBER = 1;
    private boolean hasKeycode;
    private int keycode_ = 0;
    public boolean hasKeycode() { return hasKeycode; }
    public int getKeycode() { return keycode_; }
    
    // required int32 quantity = 2;
    public static final int QUANTITY_FIELD_NUMBER = 2;
    private boolean hasQuantity;
    private int quantity_ = 0;
    public boolean hasQuantity() { return hasQuantity; }
    public int getQuantity() { return quantity_; }
    
    public final boolean isInitialized() {
      if (!hasKeycode) return false;
      if (!hasQuantity) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasKeycode()) {
        output.writeInt32(1, getKeycode());
      }
      if (hasQuantity()) {
        output.writeInt32(2, getQuantity());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKeycode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getKeycode());
      }
      if (hasQuantity()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getQuantity());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static Sales3.StoreSales3.Order parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Sales3.StoreSales3.Order parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Sales3.StoreSales3.Order parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Sales3.StoreSales3.Order parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Sales3.StoreSales3.Order parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Sales3.StoreSales3.Order parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Sales3.StoreSales3.Order parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static Sales3.StoreSales3.Order parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Sales3.StoreSales3.Order parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Sales3.StoreSales3.Order parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Sales3.StoreSales3.Order prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private Sales3.StoreSales3.Order result;
      
      // Construct using Sales3.StoreSales3.Order.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new Sales3.StoreSales3.Order();
        return builder;
      }
      
      protected Sales3.StoreSales3.Order internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new Sales3.StoreSales3.Order();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Sales3.StoreSales3.Order.getDescriptor();
      }
      
      public Sales3.StoreSales3.Order getDefaultInstanceForType() {
        return Sales3.StoreSales3.Order.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public Sales3.StoreSales3.Order build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private Sales3.StoreSales3.Order buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public Sales3.StoreSales3.Order buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        Sales3.StoreSales3.Order returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Sales3.StoreSales3.Order) {
          return mergeFrom((Sales3.StoreSales3.Order)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Sales3.StoreSales3.Order other) {
        if (other == Sales3.StoreSales3.Order.getDefaultInstance()) return this;
        if (other.hasKeycode()) {
          setKeycode(other.getKeycode());
        }
        if (other.hasQuantity()) {
          setQuantity(other.getQuantity());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setKeycode(input.readInt32());
              break;
            }
            case 16: {
              setQuantity(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required int32 keycode = 1;
      public boolean hasKeycode() {
        return result.hasKeycode();
      }
      public int getKeycode() {
        return result.getKeycode();
      }
      public Builder setKeycode(int value) {
        result.hasKeycode = true;
        result.keycode_ = value;
        return this;
      }
      public Builder clearKeycode() {
        result.hasKeycode = false;
        result.keycode_ = 0;
        return this;
      }
      
      // required int32 quantity = 2;
      public boolean hasQuantity() {
        return result.hasQuantity();
      }
      public int getQuantity() {
        return result.getQuantity();
      }
      public Builder setQuantity(int value) {
        result.hasQuantity = true;
        result.quantity_ = value;
        return this;
      }
      public Builder clearQuantity() {
        result.hasQuantity = false;
        result.quantity_ = 0;
        return this;
      }
    }
    
    static {
      Sales3.StoreSales3.getDescriptor();
    }
    
    static {
      Sales3.StoreSales3.internalForceInit();
    }
  }
  
  public static final class Summary extends
      com.google.protobuf.GeneratedMessage {
    // Use Summary.newBuilder() to construct.
    private Summary() {}
    
    private static final Summary defaultInstance = new Summary();
    public static Summary getDefaultInstance() {
      return defaultInstance;
    }
    
    public Summary getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Sales3.StoreSales3.internal_static_Sales3_Summary_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Sales3.StoreSales3.internal_static_Sales3_Summary_fieldAccessorTable;
    }
    
    // required int32 quantity = 1;
    public static final int QUANTITY_FIELD_NUMBER = 1;
    private boolean hasQuantity;
    private int quantity_ = 0;
    public boolean hasQuantity() { return hasQuantity; }
    public int getQuantity() { return quantity_; }
    
    // required int64 price = 2;
    public static final int PRICE_FIELD_NUMBER = 2;
    private boolean hasPrice;
    private long price_ = 0L;
    public boolean hasPrice() { return hasPrice; }
    public long getPrice() { return price_; }
    
    // required int32 count = 3;
    public static final int COUNT_FIELD_NUMBER = 3;
    private boolean hasCount;
    private int count_ = 0;
    public boolean hasCount() { return hasCount; }
    public int getCount() { return count_; }
    
    public final boolean isInitialized() {
      if (!hasQuantity) return false;
      if (!hasPrice) return false;
      if (!hasCount) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasQuantity()) {
        output.writeInt32(1, getQuantity());
      }
      if (hasPrice()) {
        output.writeInt64(2, getPrice());
      }
      if (hasCount()) {
        output.writeInt32(3, getCount());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasQuantity()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getQuantity());
      }
      if (hasPrice()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getPrice());
      }
      if (hasCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getCount());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static Sales3.StoreSales3.Summary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Sales3.StoreSales3.Summary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Sales3.StoreSales3.Summary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Sales3.StoreSales3.Summary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Sales3.StoreSales3.Summary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Sales3.StoreSales3.Summary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Sales3.StoreSales3.Summary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static Sales3.StoreSales3.Summary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Sales3.StoreSales3.Summary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Sales3.StoreSales3.Summary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Sales3.StoreSales3.Summary prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private Sales3.StoreSales3.Summary result;
      
      // Construct using Sales3.StoreSales3.Summary.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new Sales3.StoreSales3.Summary();
        return builder;
      }
      
      protected Sales3.StoreSales3.Summary internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new Sales3.StoreSales3.Summary();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Sales3.StoreSales3.Summary.getDescriptor();
      }
      
      public Sales3.StoreSales3.Summary getDefaultInstanceForType() {
        return Sales3.StoreSales3.Summary.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public Sales3.StoreSales3.Summary build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private Sales3.StoreSales3.Summary buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public Sales3.StoreSales3.Summary buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        Sales3.StoreSales3.Summary returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Sales3.StoreSales3.Summary) {
          return mergeFrom((Sales3.StoreSales3.Summary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Sales3.StoreSales3.Summary other) {
        if (other == Sales3.StoreSales3.Summary.getDefaultInstance()) return this;
        if (other.hasQuantity()) {
          setQuantity(other.getQuantity());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setQuantity(input.readInt32());
              break;
            }
            case 16: {
              setPrice(input.readInt64());
              break;
            }
            case 24: {
              setCount(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required int32 quantity = 1;
      public boolean hasQuantity() {
        return result.hasQuantity();
      }
      public int getQuantity() {
        return result.getQuantity();
      }
      public Builder setQuantity(int value) {
        result.hasQuantity = true;
        result.quantity_ = value;
        return this;
      }
      public Builder clearQuantity() {
        result.hasQuantity = false;
        result.quantity_ = 0;
        return this;
      }
      
      // required int64 price = 2;
      public boolean hasPrice() {
        return result.hasPrice();
      }
      public long getPrice() {
        return result.getPrice();
      }
      public Builder setPrice(long value) {
        result.hasPrice = true;
        result.price_ = value;
        return this;
      }
      public Builder clearPrice() {
        result.hasPrice = false;
        result.price_ = 0L;
        return this;
      }
      
      // required int32 count = 3;
      public boolean hasCount() {
        return result.hasCount();
      }
      public int getCount() {
        return result.getCount();
      }
      public Builder setCount(int value) {
        result.hasCount = true;
        result.count_ = value;
        return this;
      }
      public Builder clearCount() {
        result.hasCount = false;
        result.count_ = 0;
        return this;
      }
    }
    
    static {
      Sales3.StoreSales3.getDescriptor();
    }
    
    static {
      Sales3.StoreSales3.internalForceInit();
    }
  }
  
  public static final class Deptartment extends
      com.google.protobuf.GeneratedMessage {
    // Use Deptartment.newBuilder() to construct.
    private Deptartment() {}
    
    private static final Deptartment defaultInstance = new Deptartment();
    public static Deptartment getDefaultInstance() {
      return defaultInstance;
    }
    
    public Deptartment getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Sales3.StoreSales3.internal_static_Sales3_Deptartment_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Sales3.StoreSales3.internal_static_Sales3_Deptartment_fieldAccessorTable;
    }
    
    // required int32 department = 1;
    public static final int DEPARTMENT_FIELD_NUMBER = 1;
    private boolean hasDepartment;
    private int department_ = 0;
    public boolean hasDepartment() { return hasDepartment; }
    public int getDepartment() { return department_; }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // repeated .Sales3.Product product = 3;
    public static final int PRODUCT_FIELD_NUMBER = 3;
    private java.util.List<Sales3.StoreSales3.Product> product_ =
      java.util.Collections.emptyList();
    public java.util.List<Sales3.StoreSales3.Product> getProductList() {
      return product_;
    }
    public int getProductCount() { return product_.size(); }
    public Sales3.StoreSales3.Product getProduct(int index) {
      return product_.get(index);
    }
    
    // optional .Sales3.Summary summary = 4;
    public static final int SUMMARY_FIELD_NUMBER = 4;
    private boolean hasSummary;
    private Sales3.StoreSales3.Summary summary_ = Sales3.StoreSales3.Summary.getDefaultInstance();
    public boolean hasSummary() { return hasSummary; }
    public Sales3.StoreSales3.Summary getSummary() { return summary_; }
    
    public final boolean isInitialized() {
      if (!hasDepartment) return false;
      if (!hasName) return false;
      for (Sales3.StoreSales3.Product element : getProductList()) {
        if (!element.isInitialized()) return false;
      }
      if (hasSummary()) {
        if (!getSummary().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasDepartment()) {
        output.writeInt32(1, getDepartment());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      for (Sales3.StoreSales3.Product element : getProductList()) {
        output.writeMessage(3, element);
      }
      if (hasSummary()) {
        output.writeMessage(4, getSummary());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasDepartment()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getDepartment());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      for (Sales3.StoreSales3.Product element : getProductList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      if (hasSummary()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getSummary());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static Sales3.StoreSales3.Deptartment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Sales3.StoreSales3.Deptartment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Sales3.StoreSales3.Deptartment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Sales3.StoreSales3.Deptartment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Sales3.StoreSales3.Deptartment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Sales3.StoreSales3.Deptartment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Sales3.StoreSales3.Deptartment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static Sales3.StoreSales3.Deptartment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Sales3.StoreSales3.Deptartment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Sales3.StoreSales3.Deptartment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Sales3.StoreSales3.Deptartment prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private Sales3.StoreSales3.Deptartment result;
      
      // Construct using Sales3.StoreSales3.Deptartment.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new Sales3.StoreSales3.Deptartment();
        return builder;
      }
      
      protected Sales3.StoreSales3.Deptartment internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new Sales3.StoreSales3.Deptartment();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Sales3.StoreSales3.Deptartment.getDescriptor();
      }
      
      public Sales3.StoreSales3.Deptartment getDefaultInstanceForType() {
        return Sales3.StoreSales3.Deptartment.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public Sales3.StoreSales3.Deptartment build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private Sales3.StoreSales3.Deptartment buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public Sales3.StoreSales3.Deptartment buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.product_ != java.util.Collections.EMPTY_LIST) {
          result.product_ =
            java.util.Collections.unmodifiableList(result.product_);
        }
        Sales3.StoreSales3.Deptartment returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Sales3.StoreSales3.Deptartment) {
          return mergeFrom((Sales3.StoreSales3.Deptartment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Sales3.StoreSales3.Deptartment other) {
        if (other == Sales3.StoreSales3.Deptartment.getDefaultInstance()) return this;
        if (other.hasDepartment()) {
          setDepartment(other.getDepartment());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (!other.product_.isEmpty()) {
          if (result.product_.isEmpty()) {
            result.product_ = new java.util.ArrayList<Sales3.StoreSales3.Product>();
          }
          result.product_.addAll(other.product_);
        }
        if (other.hasSummary()) {
          mergeSummary(other.getSummary());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setDepartment(input.readInt32());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
            case 26: {
              Sales3.StoreSales3.Product.Builder subBuilder = Sales3.StoreSales3.Product.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addProduct(subBuilder.buildPartial());
              break;
            }
            case 34: {
              Sales3.StoreSales3.Summary.Builder subBuilder = Sales3.StoreSales3.Summary.newBuilder();
              if (hasSummary()) {
                subBuilder.mergeFrom(getSummary());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSummary(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required int32 department = 1;
      public boolean hasDepartment() {
        return result.hasDepartment();
      }
      public int getDepartment() {
        return result.getDepartment();
      }
      public Builder setDepartment(int value) {
        result.hasDepartment = true;
        result.department_ = value;
        return this;
      }
      public Builder clearDepartment() {
        result.hasDepartment = false;
        result.department_ = 0;
        return this;
      }
      
      // required string name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // repeated .Sales3.Product product = 3;
      public java.util.List<Sales3.StoreSales3.Product> getProductList() {
        return java.util.Collections.unmodifiableList(result.product_);
      }
      public int getProductCount() {
        return result.getProductCount();
      }
      public Sales3.StoreSales3.Product getProduct(int index) {
        return result.getProduct(index);
      }
      public Builder setProduct(int index, Sales3.StoreSales3.Product value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.product_.set(index, value);
        return this;
      }
      public Builder setProduct(int index, Sales3.StoreSales3.Product.Builder builderForValue) {
        result.product_.set(index, builderForValue.build());
        return this;
      }
      public Builder addProduct(Sales3.StoreSales3.Product value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.product_.isEmpty()) {
          result.product_ = new java.util.ArrayList<Sales3.StoreSales3.Product>();
        }
        result.product_.add(value);
        return this;
      }
      public Builder addProduct(Sales3.StoreSales3.Product.Builder builderForValue) {
        if (result.product_.isEmpty()) {
          result.product_ = new java.util.ArrayList<Sales3.StoreSales3.Product>();
        }
        result.product_.add(builderForValue.build());
        return this;
      }
      public Builder addAllProduct(
          java.lang.Iterable<? extends Sales3.StoreSales3.Product> values) {
        if (result.product_.isEmpty()) {
          result.product_ = new java.util.ArrayList<Sales3.StoreSales3.Product>();
        }
        super.addAll(values, result.product_);
        return this;
      }
      public Builder clearProduct() {
        result.product_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional .Sales3.Summary summary = 4;
      public boolean hasSummary() {
        return result.hasSummary();
      }
      public Sales3.StoreSales3.Summary getSummary() {
        return result.getSummary();
      }
      public Builder setSummary(Sales3.StoreSales3.Summary value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasSummary = true;
        result.summary_ = value;
        return this;
      }
      public Builder setSummary(Sales3.StoreSales3.Summary.Builder builderForValue) {
        result.hasSummary = true;
        result.summary_ = builderForValue.build();
        return this;
      }
      public Builder mergeSummary(Sales3.StoreSales3.Summary value) {
        if (result.hasSummary() &&
            result.summary_ != Sales3.StoreSales3.Summary.getDefaultInstance()) {
          result.summary_ =
            Sales3.StoreSales3.Summary.newBuilder(result.summary_).mergeFrom(value).buildPartial();
        } else {
          result.summary_ = value;
        }
        result.hasSummary = true;
        return this;
      }
      public Builder clearSummary() {
        result.hasSummary = false;
        result.summary_ = Sales3.StoreSales3.Summary.getDefaultInstance();
        return this;
      }
    }
    
    static {
      Sales3.StoreSales3.getDescriptor();
    }
    
    static {
      Sales3.StoreSales3.internalForceInit();
    }
  }
  
  public static final class Store extends
      com.google.protobuf.GeneratedMessage {
    // Use Store.newBuilder() to construct.
    private Store() {}
    
    private static final Store defaultInstance = new Store();
    public static Store getDefaultInstance() {
      return defaultInstance;
    }
    
    public Store getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Sales3.StoreSales3.internal_static_Sales3_Store_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Sales3.StoreSales3.internal_static_Sales3_Store_fieldAccessorTable;
    }
    
    // required int32 store = 1;
    public static final int STORE_FIELD_NUMBER = 1;
    private boolean hasStore;
    private int store_ = 0;
    public boolean hasStore() { return hasStore; }
    public int getStore() { return store_; }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // repeated .Sales3.Deptartment department = 3;
    public static final int DEPARTMENT_FIELD_NUMBER = 3;
    private java.util.List<Sales3.StoreSales3.Deptartment> department_ =
      java.util.Collections.emptyList();
    public java.util.List<Sales3.StoreSales3.Deptartment> getDepartmentList() {
      return department_;
    }
    public int getDepartmentCount() { return department_.size(); }
    public Sales3.StoreSales3.Deptartment getDepartment(int index) {
      return department_.get(index);
    }
    
    // repeated .Sales3.Order order = 4;
    public static final int ORDER_FIELD_NUMBER = 4;
    private java.util.List<Sales3.StoreSales3.Order> order_ =
      java.util.Collections.emptyList();
    public java.util.List<Sales3.StoreSales3.Order> getOrderList() {
      return order_;
    }
    public int getOrderCount() { return order_.size(); }
    public Sales3.StoreSales3.Order getOrder(int index) {
      return order_.get(index);
    }
    
    // optional .Sales3.Summary summary = 5;
    public static final int SUMMARY_FIELD_NUMBER = 5;
    private boolean hasSummary;
    private Sales3.StoreSales3.Summary summary_ = Sales3.StoreSales3.Summary.getDefaultInstance();
    public boolean hasSummary() { return hasSummary; }
    public Sales3.StoreSales3.Summary getSummary() { return summary_; }
    
    public final boolean isInitialized() {
      if (!hasStore) return false;
      if (!hasName) return false;
      for (Sales3.StoreSales3.Deptartment element : getDepartmentList()) {
        if (!element.isInitialized()) return false;
      }
      for (Sales3.StoreSales3.Order element : getOrderList()) {
        if (!element.isInitialized()) return false;
      }
      if (hasSummary()) {
        if (!getSummary().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasStore()) {
        output.writeInt32(1, getStore());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      for (Sales3.StoreSales3.Deptartment element : getDepartmentList()) {
        output.writeMessage(3, element);
      }
      for (Sales3.StoreSales3.Order element : getOrderList()) {
        output.writeMessage(4, element);
      }
      if (hasSummary()) {
        output.writeMessage(5, getSummary());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasStore()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getStore());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      for (Sales3.StoreSales3.Deptartment element : getDepartmentList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      for (Sales3.StoreSales3.Order element : getOrderList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, element);
      }
      if (hasSummary()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getSummary());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static Sales3.StoreSales3.Store parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Sales3.StoreSales3.Store parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Sales3.StoreSales3.Store parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Sales3.StoreSales3.Store parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Sales3.StoreSales3.Store parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Sales3.StoreSales3.Store parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Sales3.StoreSales3.Store parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static Sales3.StoreSales3.Store parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Sales3.StoreSales3.Store parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Sales3.StoreSales3.Store parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Sales3.StoreSales3.Store prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private Sales3.StoreSales3.Store result;
      
      // Construct using Sales3.StoreSales3.Store.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new Sales3.StoreSales3.Store();
        return builder;
      }
      
      protected Sales3.StoreSales3.Store internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new Sales3.StoreSales3.Store();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Sales3.StoreSales3.Store.getDescriptor();
      }
      
      public Sales3.StoreSales3.Store getDefaultInstanceForType() {
        return Sales3.StoreSales3.Store.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public Sales3.StoreSales3.Store build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private Sales3.StoreSales3.Store buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public Sales3.StoreSales3.Store buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.department_ != java.util.Collections.EMPTY_LIST) {
          result.department_ =
            java.util.Collections.unmodifiableList(result.department_);
        }
        if (result.order_ != java.util.Collections.EMPTY_LIST) {
          result.order_ =
            java.util.Collections.unmodifiableList(result.order_);
        }
        Sales3.StoreSales3.Store returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Sales3.StoreSales3.Store) {
          return mergeFrom((Sales3.StoreSales3.Store)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Sales3.StoreSales3.Store other) {
        if (other == Sales3.StoreSales3.Store.getDefaultInstance()) return this;
        if (other.hasStore()) {
          setStore(other.getStore());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (!other.department_.isEmpty()) {
          if (result.department_.isEmpty()) {
            result.department_ = new java.util.ArrayList<Sales3.StoreSales3.Deptartment>();
          }
          result.department_.addAll(other.department_);
        }
        if (!other.order_.isEmpty()) {
          if (result.order_.isEmpty()) {
            result.order_ = new java.util.ArrayList<Sales3.StoreSales3.Order>();
          }
          result.order_.addAll(other.order_);
        }
        if (other.hasSummary()) {
          mergeSummary(other.getSummary());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setStore(input.readInt32());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
            case 26: {
              Sales3.StoreSales3.Deptartment.Builder subBuilder = Sales3.StoreSales3.Deptartment.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addDepartment(subBuilder.buildPartial());
              break;
            }
            case 34: {
              Sales3.StoreSales3.Order.Builder subBuilder = Sales3.StoreSales3.Order.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addOrder(subBuilder.buildPartial());
              break;
            }
            case 42: {
              Sales3.StoreSales3.Summary.Builder subBuilder = Sales3.StoreSales3.Summary.newBuilder();
              if (hasSummary()) {
                subBuilder.mergeFrom(getSummary());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSummary(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required int32 store = 1;
      public boolean hasStore() {
        return result.hasStore();
      }
      public int getStore() {
        return result.getStore();
      }
      public Builder setStore(int value) {
        result.hasStore = true;
        result.store_ = value;
        return this;
      }
      public Builder clearStore() {
        result.hasStore = false;
        result.store_ = 0;
        return this;
      }
      
      // required string name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // repeated .Sales3.Deptartment department = 3;
      public java.util.List<Sales3.StoreSales3.Deptartment> getDepartmentList() {
        return java.util.Collections.unmodifiableList(result.department_);
      }
      public int getDepartmentCount() {
        return result.getDepartmentCount();
      }
      public Sales3.StoreSales3.Deptartment getDepartment(int index) {
        return result.getDepartment(index);
      }
      public Builder setDepartment(int index, Sales3.StoreSales3.Deptartment value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.department_.set(index, value);
        return this;
      }
      public Builder setDepartment(int index, Sales3.StoreSales3.Deptartment.Builder builderForValue) {
        result.department_.set(index, builderForValue.build());
        return this;
      }
      public Builder addDepartment(Sales3.StoreSales3.Deptartment value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.department_.isEmpty()) {
          result.department_ = new java.util.ArrayList<Sales3.StoreSales3.Deptartment>();
        }
        result.department_.add(value);
        return this;
      }
      public Builder addDepartment(Sales3.StoreSales3.Deptartment.Builder builderForValue) {
        if (result.department_.isEmpty()) {
          result.department_ = new java.util.ArrayList<Sales3.StoreSales3.Deptartment>();
        }
        result.department_.add(builderForValue.build());
        return this;
      }
      public Builder addAllDepartment(
          java.lang.Iterable<? extends Sales3.StoreSales3.Deptartment> values) {
        if (result.department_.isEmpty()) {
          result.department_ = new java.util.ArrayList<Sales3.StoreSales3.Deptartment>();
        }
        super.addAll(values, result.department_);
        return this;
      }
      public Builder clearDepartment() {
        result.department_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .Sales3.Order order = 4;
      public java.util.List<Sales3.StoreSales3.Order> getOrderList() {
        return java.util.Collections.unmodifiableList(result.order_);
      }
      public int getOrderCount() {
        return result.getOrderCount();
      }
      public Sales3.StoreSales3.Order getOrder(int index) {
        return result.getOrder(index);
      }
      public Builder setOrder(int index, Sales3.StoreSales3.Order value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.order_.set(index, value);
        return this;
      }
      public Builder setOrder(int index, Sales3.StoreSales3.Order.Builder builderForValue) {
        result.order_.set(index, builderForValue.build());
        return this;
      }
      public Builder addOrder(Sales3.StoreSales3.Order value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.order_.isEmpty()) {
          result.order_ = new java.util.ArrayList<Sales3.StoreSales3.Order>();
        }
        result.order_.add(value);
        return this;
      }
      public Builder addOrder(Sales3.StoreSales3.Order.Builder builderForValue) {
        if (result.order_.isEmpty()) {
          result.order_ = new java.util.ArrayList<Sales3.StoreSales3.Order>();
        }
        result.order_.add(builderForValue.build());
        return this;
      }
      public Builder addAllOrder(
          java.lang.Iterable<? extends Sales3.StoreSales3.Order> values) {
        if (result.order_.isEmpty()) {
          result.order_ = new java.util.ArrayList<Sales3.StoreSales3.Order>();
        }
        super.addAll(values, result.order_);
        return this;
      }
      public Builder clearOrder() {
        result.order_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional .Sales3.Summary summary = 5;
      public boolean hasSummary() {
        return result.hasSummary();
      }
      public Sales3.StoreSales3.Summary getSummary() {
        return result.getSummary();
      }
      public Builder setSummary(Sales3.StoreSales3.Summary value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasSummary = true;
        result.summary_ = value;
        return this;
      }
      public Builder setSummary(Sales3.StoreSales3.Summary.Builder builderForValue) {
        result.hasSummary = true;
        result.summary_ = builderForValue.build();
        return this;
      }
      public Builder mergeSummary(Sales3.StoreSales3.Summary value) {
        if (result.hasSummary() &&
            result.summary_ != Sales3.StoreSales3.Summary.getDefaultInstance()) {
          result.summary_ =
            Sales3.StoreSales3.Summary.newBuilder(result.summary_).mergeFrom(value).buildPartial();
        } else {
          result.summary_ = value;
        }
        result.hasSummary = true;
        return this;
      }
      public Builder clearSummary() {
        result.hasSummary = false;
        result.summary_ = Sales3.StoreSales3.Summary.getDefaultInstance();
        return this;
      }
    }
    
    static {
      Sales3.StoreSales3.getDescriptor();
    }
    
    static {
      Sales3.StoreSales3.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Sales3_Product_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Sales3_Product_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Sales3_Order_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Sales3_Order_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Sales3_Summary_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Sales3_Summary_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Sales3_Deptartment_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Sales3_Deptartment_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Sales3_Store_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Sales3_Store_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021StoreSales3.proto\022\006Sales3\"M\n\007Product\022\017" +
      "\n\007keycode\030\001 \002(\005\022\020\n\010saleDate\030\002 \002(\005\022\020\n\010qua" +
      "ntity\030\003 \002(\005\022\r\n\005price\030\004 \002(\003\"*\n\005Order\022\017\n\007k" +
      "eycode\030\001 \002(\005\022\020\n\010quantity\030\002 \002(\005\"9\n\007Summar" +
      "y\022\020\n\010quantity\030\001 \002(\005\022\r\n\005price\030\002 \002(\003\022\r\n\005co" +
      "unt\030\003 \002(\005\"s\n\013Deptartment\022\022\n\ndepartment\030\001" +
      " \002(\005\022\014\n\004name\030\002 \002(\t\022 \n\007product\030\003 \003(\0132\017.Sa" +
      "les3.Product\022 \n\007summary\030\004 \001(\0132\017.Sales3.S" +
      "ummary\"\215\001\n\005Store\022\r\n\005store\030\001 \002(\005\022\014\n\004name\030" +
      "\002 \002(\t\022\'\n\ndepartment\030\003 \003(\0132\023.Sales3.Depta",
      "rtment\022\034\n\005order\030\004 \003(\0132\r.Sales3.Order\022 \n\007" +
      "summary\030\005 \001(\0132\017.Sales3.SummaryB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Sales3_Product_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Sales3_Product_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Sales3_Product_descriptor,
              new java.lang.String[] { "Keycode", "SaleDate", "Quantity", "Price", },
              Sales3.StoreSales3.Product.class,
              Sales3.StoreSales3.Product.Builder.class);
          internal_static_Sales3_Order_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Sales3_Order_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Sales3_Order_descriptor,
              new java.lang.String[] { "Keycode", "Quantity", },
              Sales3.StoreSales3.Order.class,
              Sales3.StoreSales3.Order.Builder.class);
          internal_static_Sales3_Summary_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Sales3_Summary_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Sales3_Summary_descriptor,
              new java.lang.String[] { "Quantity", "Price", "Count", },
              Sales3.StoreSales3.Summary.class,
              Sales3.StoreSales3.Summary.Builder.class);
          internal_static_Sales3_Deptartment_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_Sales3_Deptartment_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Sales3_Deptartment_descriptor,
              new java.lang.String[] { "Department", "Name", "Product", "Summary", },
              Sales3.StoreSales3.Deptartment.class,
              Sales3.StoreSales3.Deptartment.Builder.class);
          internal_static_Sales3_Store_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_Sales3_Store_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Sales3_Store_descriptor,
              new java.lang.String[] { "Store", "Name", "Department", "Order", "Summary", },
              Sales3.StoreSales3.Store.class,
              Sales3.StoreSales3.Store.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
