useFixture(default)

def test():
	from Modules import commonBits
	java_recorded_version = '1.6.0_17'

	if window('Protocol Buffer Editor'):
		select('FileChooser', commonBits.sampleDir() +  'Ams_LocDownload_20041228.bin')
		click('Edit1')
		select('Table', 'cell:2|Loc_Nbr,0(5839)')
		rightclick('Table', '1|Brand_Id,9')
##		select('Table', 'cell:2|Loc_Nbr,0(5839)')
		select_menu('Edit Record')
##		select('Table1', 'cell:2|Loc_Nbr,0(5839)')
##		select('Table', '')
		rightclick('Table', 'Data,0')
		select_menu('Hide Column')
##		select('Table', '')
		rightclick('Table', 'Data,1')
		select_menu('Hide Column')
##		select('Table', '')
		rightclick('Table', 'Data,3')
		select_menu('Hide Column')
##		select('Table', '')
		rightclick('Table', 'Data,6')
		select_menu('Hide Column')
		select('Table', 'cell:Data,3(Marayong)')
		assert_p('Table', 'Content', '[[Loc_Nbr, 2, , 5052, 5052], [Loc_Name, 4, , Eastwood, Eastwood], [Loc_Addr_Ln1, 5, , Marayong Offsite Reserve, Marayong Offsite Reserve], [Loc_Addr_Ln3, 7, , Marayong, Marayong], [Loc_Postcode, 8, , 2148, 2148], [Loc_State, 9, , NSW, NSW]]')
		select('Table', 'cell:Data,3(Marayong)')
		select_menu('Edit>>Show / Hide Fields')
##		select('Table1', 'cell:Data,3(Marayong)')
		assert_p('Table', 'Content', '[[Brand_Id, false], [Loc_Nbr, true], [Loc_Type, false], [Loc_Name, true], [Loc_Addr_Ln1, true], [Loc_Addr_Ln2, false], [Loc_Addr_Ln3, true], [Loc_Postcode, true], [Loc_State, true], [Loc_Actv_Ind, true]]')
		click('BasicInternalFrameTitlePane$NoFocusButton2')
		select('Table', 'cell:Data,3(Marayong)')
		select('Table', 'cell:Data,3(Marayong)')
		select_menu('Window>>Ams_LocDownload_20041228.bin>>Record: ')
		select('Table', 'cell:Data,3(Marayong)')
		rightclick('Table', 'Data,4')
		select_menu('Show LocationsFields>>Loc_Actv_Ind')
		assert_p('Table', 'Content', '[[Loc_Nbr, 2, , 5052, 5052], [Loc_Name, 4, , Eastwood, Eastwood], [Loc_Addr_Ln1, 5, , Marayong Offsite Reserve, Marayong Offsite Reserve], [Loc_Addr_Ln3, 7, , Marayong, Marayong], [Loc_Postcode, 8, , 2148, 2148], [Loc_State, 9, , NSW, NSW], [Loc_Actv_Ind, 10, , A, A]]')
##		select('Table', '')
		rightclick('Table', 'Data,4')
		select_menu('Show LocationsFields>>Loc_Addr_Ln2')
		select('Table', 'cell:Data,5(2148)')
		assert_p('Table', 'Content', '[[Loc_Nbr, 2, , 5052, 5052], [Loc_Name, 4, , Eastwood, Eastwood], [Loc_Addr_Ln1, 5, , Marayong Offsite Reserve, Marayong Offsite Reserve], [Loc_Addr_Ln2, 6, , 11 Melissa Place, 11 Melissa Place], [Loc_Addr_Ln3, 7, , Marayong, Marayong], [Loc_Postcode, 8, , 2148, 2148], [Loc_State, 9, , NSW, NSW], [Loc_Actv_Ind, 10, , A, A]]')
		select('Table', 'cell:Data,5(2148)')
		rightclick('Table', 'Data,6')
		select_menu('Show LocationsFields>>Loc_Type')
		select('Table', 'cell:Data,5(Marayong)')
		assert_p('Table', 'Content', '[[Loc_Nbr, 2, , 5052, 5052], [Loc_Type, 3, , ST, ST], [Loc_Name, 4, , Eastwood, Eastwood], [Loc_Addr_Ln1, 5, , Marayong Offsite Reserve, Marayong Offsite Reserve], [Loc_Addr_Ln2, 6, , 11 Melissa Place, 11 Melissa Place], [Loc_Addr_Ln3, 7, , Marayong, Marayong], [Loc_Postcode, 8, , 2148, 2148], [Loc_State, 9, , NSW, NSW], [Loc_Actv_Ind, 10, , A, A]]')
		select('Table', 'cell:Data,5(Marayong)')
		select_menu('Edit>>Show / Hide Fields')
##		select('Table1', 'cell:Data,5(Marayong)')
		assert_p('Table', 'Content', '[[Brand_Id, false], [Loc_Nbr, true], [Loc_Type, true], [Loc_Name, true], [Loc_Addr_Ln1, true], [Loc_Addr_Ln2, true], [Loc_Addr_Ln3, true], [Loc_Postcode, true], [Loc_State, true], [Loc_Actv_Ind, true]]')
		click('BasicInternalFrameTitlePane$NoFocusButton2')
		select('Table', 'cell:Data,5(Marayong)')
#		select('Table', 'cell:Data,5(Marayong)')
		select_menu('Window>>Ams_LocDownload_20041228.bin>>Record: ')
		select('Table', 'cell:Data,5(Marayong)')
		rightclick('Table', 'Data,6')
		select_menu('Show LocationsFields>>Brand_Id')
		assert_p('Table', 'Content', '[[Brand_Id, 1, , TAR, TAR], [Loc_Nbr, 2, , 5052, 5052], [Loc_Type, 3, , ST, ST], [Loc_Name, 4, , Eastwood, Eastwood], [Loc_Addr_Ln1, 5, , Marayong Offsite Reserve, Marayong Offsite Reserve], [Loc_Addr_Ln2, 6, , 11 Melissa Place, 11 Melissa Place], [Loc_Addr_Ln3, 7, , Marayong, Marayong], [Loc_Postcode, 8, , 2148, 2148], [Loc_State, 9, , NSW, NSW], [Loc_Actv_Ind, 10, , A, A]]')
		click('BasicInternalFrameTitlePane$NoFocusButton2')
		select('Table', 'cell:2|Loc_Nbr,0(5839)')
	close()
