// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StoreSales.proto

package net.sf.RecordEditor.ProtoBuf.re.Test.Sales2;

public final class StoreSales {
  private StoreSales() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProductOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 keycode = 1;
    boolean hasKeycode();
    int getKeycode();
    
    // required int32 saleDate = 2;
    boolean hasSaleDate();
    int getSaleDate();
    
    // required int32 quantity = 3;
    boolean hasQuantity();
    int getQuantity();
    
    // required int64 price = 4;
    boolean hasPrice();
    long getPrice();
  }
  public static final class Product extends
      com.google.protobuf.GeneratedMessage
      implements ProductOrBuilder {
    // Use Product.newBuilder() to construct.
    private Product(Builder builder) {
      super(builder);
    }
    private Product(boolean noInit) {}
    
    private static final Product defaultInstance;
    public static Product getDefaultInstance() {
      return defaultInstance;
    }
    
    public Product getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Product_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Product_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 keycode = 1;
    public static final int KEYCODE_FIELD_NUMBER = 1;
    private int keycode_;
    public boolean hasKeycode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getKeycode() {
      return keycode_;
    }
    
    // required int32 saleDate = 2;
    public static final int SALEDATE_FIELD_NUMBER = 2;
    private int saleDate_;
    public boolean hasSaleDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getSaleDate() {
      return saleDate_;
    }
    
    // required int32 quantity = 3;
    public static final int QUANTITY_FIELD_NUMBER = 3;
    private int quantity_;
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getQuantity() {
      return quantity_;
    }
    
    // required int64 price = 4;
    public static final int PRICE_FIELD_NUMBER = 4;
    private long price_;
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getPrice() {
      return price_;
    }
    
    private void initFields() {
      keycode_ = 0;
      saleDate_ = 0;
      quantity_ = 0;
      price_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasKeycode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSaleDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQuantity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, keycode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, saleDate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, quantity_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, price_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, keycode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, saleDate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, quantity_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, price_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.ProductOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Product_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Product_fieldAccessorTable;
      }
      
      // Construct using net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        keycode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        saleDate_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        quantity_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        price_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product.getDescriptor();
      }
      
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product getDefaultInstanceForType() {
        return net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product.getDefaultInstance();
      }
      
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product build() {
        net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product buildPartial() {
        net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product result = new net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.keycode_ = keycode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.saleDate_ = saleDate_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.quantity_ = quantity_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.price_ = price_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product) {
          return mergeFrom((net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product other) {
        if (other == net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product.getDefaultInstance()) return this;
        if (other.hasKeycode()) {
          setKeycode(other.getKeycode());
        }
        if (other.hasSaleDate()) {
          setSaleDate(other.getSaleDate());
        }
        if (other.hasQuantity()) {
          setQuantity(other.getQuantity());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasKeycode()) {
          
          return false;
        }
        if (!hasSaleDate()) {
          
          return false;
        }
        if (!hasQuantity()) {
          
          return false;
        }
        if (!hasPrice()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              keycode_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              saleDate_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              quantity_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              price_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 keycode = 1;
      private int keycode_ ;
      public boolean hasKeycode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getKeycode() {
        return keycode_;
      }
      public Builder setKeycode(int value) {
        bitField0_ |= 0x00000001;
        keycode_ = value;
        onChanged();
        return this;
      }
      public Builder clearKeycode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        keycode_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 saleDate = 2;
      private int saleDate_ ;
      public boolean hasSaleDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getSaleDate() {
        return saleDate_;
      }
      public Builder setSaleDate(int value) {
        bitField0_ |= 0x00000002;
        saleDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearSaleDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        saleDate_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 quantity = 3;
      private int quantity_ ;
      public boolean hasQuantity() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getQuantity() {
        return quantity_;
      }
      public Builder setQuantity(int value) {
        bitField0_ |= 0x00000004;
        quantity_ = value;
        onChanged();
        return this;
      }
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000004);
        quantity_ = 0;
        onChanged();
        return this;
      }
      
      // required int64 price = 4;
      private long price_ ;
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getPrice() {
        return price_;
      }
      public Builder setPrice(long value) {
        bitField0_ |= 0x00000008;
        price_ = value;
        onChanged();
        return this;
      }
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000008);
        price_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.Product)
    }
    
    static {
      defaultInstance = new Product(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.Product)
  }
  
  public interface DeptartmentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 department = 1;
    boolean hasDepartment();
    int getDepartment();
    
    // required string name = 2;
    boolean hasName();
    String getName();
    
    // repeated .net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.Product product = 3;
    java.util.List<net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product> 
        getProductList();
    net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product getProduct(int index);
    int getProductCount();
    java.util.List<? extends net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.ProductOrBuilder> 
        getProductOrBuilderList();
    net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.ProductOrBuilder getProductOrBuilder(
        int index);
  }
  public static final class Deptartment extends
      com.google.protobuf.GeneratedMessage
      implements DeptartmentOrBuilder {
    // Use Deptartment.newBuilder() to construct.
    private Deptartment(Builder builder) {
      super(builder);
    }
    private Deptartment(boolean noInit) {}
    
    private static final Deptartment defaultInstance;
    public static Deptartment getDefaultInstance() {
      return defaultInstance;
    }
    
    public Deptartment getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Deptartment_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Deptartment_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 department = 1;
    public static final int DEPARTMENT_FIELD_NUMBER = 1;
    private int department_;
    public boolean hasDepartment() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getDepartment() {
      return department_;
    }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.Product product = 3;
    public static final int PRODUCT_FIELD_NUMBER = 3;
    private java.util.List<net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product> product_;
    public java.util.List<net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product> getProductList() {
      return product_;
    }
    public java.util.List<? extends net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.ProductOrBuilder> 
        getProductOrBuilderList() {
      return product_;
    }
    public int getProductCount() {
      return product_.size();
    }
    public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product getProduct(int index) {
      return product_.get(index);
    }
    public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.ProductOrBuilder getProductOrBuilder(
        int index) {
      return product_.get(index);
    }
    
    private void initFields() {
      department_ = 0;
      name_ = "";
      product_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDepartment()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getProductCount(); i++) {
        if (!getProduct(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, department_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      for (int i = 0; i < product_.size(); i++) {
        output.writeMessage(3, product_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, department_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      for (int i = 0; i < product_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, product_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.DeptartmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Deptartment_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Deptartment_fieldAccessorTable;
      }
      
      // Construct using net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getProductFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        department_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (productBuilder_ == null) {
          product_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          productBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment.getDescriptor();
      }
      
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment getDefaultInstanceForType() {
        return net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment.getDefaultInstance();
      }
      
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment build() {
        net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment buildPartial() {
        net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment result = new net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.department_ = department_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (productBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            product_ = java.util.Collections.unmodifiableList(product_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.product_ = product_;
        } else {
          result.product_ = productBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment) {
          return mergeFrom((net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment other) {
        if (other == net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment.getDefaultInstance()) return this;
        if (other.hasDepartment()) {
          setDepartment(other.getDepartment());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (productBuilder_ == null) {
          if (!other.product_.isEmpty()) {
            if (product_.isEmpty()) {
              product_ = other.product_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureProductIsMutable();
              product_.addAll(other.product_);
            }
            onChanged();
          }
        } else {
          if (!other.product_.isEmpty()) {
            if (productBuilder_.isEmpty()) {
              productBuilder_.dispose();
              productBuilder_ = null;
              product_ = other.product_;
              bitField0_ = (bitField0_ & ~0x00000004);
              productBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getProductFieldBuilder() : null;
            } else {
              productBuilder_.addAllMessages(other.product_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDepartment()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        for (int i = 0; i < getProductCount(); i++) {
          if (!getProduct(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              department_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product.Builder subBuilder = net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addProduct(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 department = 1;
      private int department_ ;
      public boolean hasDepartment() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getDepartment() {
        return department_;
      }
      public Builder setDepartment(int value) {
        bitField0_ |= 0x00000001;
        department_ = value;
        onChanged();
        return this;
      }
      public Builder clearDepartment() {
        bitField0_ = (bitField0_ & ~0x00000001);
        department_ = 0;
        onChanged();
        return this;
      }
      
      // required string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // repeated .net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.Product product = 3;
      private java.util.List<net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product> product_ =
        java.util.Collections.emptyList();
      private void ensureProductIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          product_ = new java.util.ArrayList<net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product>(product_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product.Builder, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.ProductOrBuilder> productBuilder_;
      
      public java.util.List<net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product> getProductList() {
        if (productBuilder_ == null) {
          return java.util.Collections.unmodifiableList(product_);
        } else {
          return productBuilder_.getMessageList();
        }
      }
      public int getProductCount() {
        if (productBuilder_ == null) {
          return product_.size();
        } else {
          return productBuilder_.getCount();
        }
      }
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product getProduct(int index) {
        if (productBuilder_ == null) {
          return product_.get(index);
        } else {
          return productBuilder_.getMessage(index);
        }
      }
      public Builder setProduct(
          int index, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product value) {
        if (productBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductIsMutable();
          product_.set(index, value);
          onChanged();
        } else {
          productBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setProduct(
          int index, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product.Builder builderForValue) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.set(index, builderForValue.build());
          onChanged();
        } else {
          productBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addProduct(net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product value) {
        if (productBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductIsMutable();
          product_.add(value);
          onChanged();
        } else {
          productBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addProduct(
          int index, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product value) {
        if (productBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductIsMutable();
          product_.add(index, value);
          onChanged();
        } else {
          productBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addProduct(
          net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product.Builder builderForValue) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.add(builderForValue.build());
          onChanged();
        } else {
          productBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addProduct(
          int index, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product.Builder builderForValue) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.add(index, builderForValue.build());
          onChanged();
        } else {
          productBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllProduct(
          java.lang.Iterable<? extends net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product> values) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          super.addAll(values, product_);
          onChanged();
        } else {
          productBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearProduct() {
        if (productBuilder_ == null) {
          product_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          productBuilder_.clear();
        }
        return this;
      }
      public Builder removeProduct(int index) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.remove(index);
          onChanged();
        } else {
          productBuilder_.remove(index);
        }
        return this;
      }
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product.Builder getProductBuilder(
          int index) {
        return getProductFieldBuilder().getBuilder(index);
      }
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.ProductOrBuilder getProductOrBuilder(
          int index) {
        if (productBuilder_ == null) {
          return product_.get(index);  } else {
          return productBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.ProductOrBuilder> 
           getProductOrBuilderList() {
        if (productBuilder_ != null) {
          return productBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(product_);
        }
      }
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product.Builder addProductBuilder() {
        return getProductFieldBuilder().addBuilder(
            net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product.getDefaultInstance());
      }
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product.Builder addProductBuilder(
          int index) {
        return getProductFieldBuilder().addBuilder(
            index, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product.getDefaultInstance());
      }
      public java.util.List<net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product.Builder> 
           getProductBuilderList() {
        return getProductFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product.Builder, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.ProductOrBuilder> 
          getProductFieldBuilder() {
        if (productBuilder_ == null) {
          productBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product.Builder, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.ProductOrBuilder>(
                  product_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          product_ = null;
        }
        return productBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.Deptartment)
    }
    
    static {
      defaultInstance = new Deptartment(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.Deptartment)
  }
  
  public interface StoreOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 store = 1;
    boolean hasStore();
    int getStore();
    
    // required string name = 2;
    boolean hasName();
    String getName();
    
    // repeated .net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.Deptartment department = 3;
    java.util.List<net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment> 
        getDepartmentList();
    net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment getDepartment(int index);
    int getDepartmentCount();
    java.util.List<? extends net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.DeptartmentOrBuilder> 
        getDepartmentOrBuilderList();
    net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.DeptartmentOrBuilder getDepartmentOrBuilder(
        int index);
  }
  public static final class Store extends
      com.google.protobuf.GeneratedMessage
      implements StoreOrBuilder {
    // Use Store.newBuilder() to construct.
    private Store(Builder builder) {
      super(builder);
    }
    private Store(boolean noInit) {}
    
    private static final Store defaultInstance;
    public static Store getDefaultInstance() {
      return defaultInstance;
    }
    
    public Store getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Store_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Store_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 store = 1;
    public static final int STORE_FIELD_NUMBER = 1;
    private int store_;
    public boolean hasStore() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getStore() {
      return store_;
    }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.Deptartment department = 3;
    public static final int DEPARTMENT_FIELD_NUMBER = 3;
    private java.util.List<net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment> department_;
    public java.util.List<net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment> getDepartmentList() {
      return department_;
    }
    public java.util.List<? extends net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.DeptartmentOrBuilder> 
        getDepartmentOrBuilderList() {
      return department_;
    }
    public int getDepartmentCount() {
      return department_.size();
    }
    public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment getDepartment(int index) {
      return department_.get(index);
    }
    public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.DeptartmentOrBuilder getDepartmentOrBuilder(
        int index) {
      return department_.get(index);
    }
    
    private void initFields() {
      store_ = 0;
      name_ = "";
      department_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasStore()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getDepartmentCount(); i++) {
        if (!getDepartment(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, store_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      for (int i = 0; i < department_.size(); i++) {
        output.writeMessage(3, department_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, store_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      for (int i = 0; i < department_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, department_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.StoreOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Store_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Store_fieldAccessorTable;
      }
      
      // Construct using net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDepartmentFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        store_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (departmentBuilder_ == null) {
          department_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          departmentBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store.getDescriptor();
      }
      
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store getDefaultInstanceForType() {
        return net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store.getDefaultInstance();
      }
      
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store build() {
        net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store buildPartial() {
        net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store result = new net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.store_ = store_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (departmentBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            department_ = java.util.Collections.unmodifiableList(department_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.department_ = department_;
        } else {
          result.department_ = departmentBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store) {
          return mergeFrom((net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store other) {
        if (other == net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store.getDefaultInstance()) return this;
        if (other.hasStore()) {
          setStore(other.getStore());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (departmentBuilder_ == null) {
          if (!other.department_.isEmpty()) {
            if (department_.isEmpty()) {
              department_ = other.department_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureDepartmentIsMutable();
              department_.addAll(other.department_);
            }
            onChanged();
          }
        } else {
          if (!other.department_.isEmpty()) {
            if (departmentBuilder_.isEmpty()) {
              departmentBuilder_.dispose();
              departmentBuilder_ = null;
              department_ = other.department_;
              bitField0_ = (bitField0_ & ~0x00000004);
              departmentBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDepartmentFieldBuilder() : null;
            } else {
              departmentBuilder_.addAllMessages(other.department_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasStore()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        for (int i = 0; i < getDepartmentCount(); i++) {
          if (!getDepartment(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              store_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment.Builder subBuilder = net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addDepartment(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 store = 1;
      private int store_ ;
      public boolean hasStore() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getStore() {
        return store_;
      }
      public Builder setStore(int value) {
        bitField0_ |= 0x00000001;
        store_ = value;
        onChanged();
        return this;
      }
      public Builder clearStore() {
        bitField0_ = (bitField0_ & ~0x00000001);
        store_ = 0;
        onChanged();
        return this;
      }
      
      // required string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // repeated .net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.Deptartment department = 3;
      private java.util.List<net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment> department_ =
        java.util.Collections.emptyList();
      private void ensureDepartmentIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          department_ = new java.util.ArrayList<net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment>(department_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment.Builder, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.DeptartmentOrBuilder> departmentBuilder_;
      
      public java.util.List<net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment> getDepartmentList() {
        if (departmentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(department_);
        } else {
          return departmentBuilder_.getMessageList();
        }
      }
      public int getDepartmentCount() {
        if (departmentBuilder_ == null) {
          return department_.size();
        } else {
          return departmentBuilder_.getCount();
        }
      }
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment getDepartment(int index) {
        if (departmentBuilder_ == null) {
          return department_.get(index);
        } else {
          return departmentBuilder_.getMessage(index);
        }
      }
      public Builder setDepartment(
          int index, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment value) {
        if (departmentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDepartmentIsMutable();
          department_.set(index, value);
          onChanged();
        } else {
          departmentBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setDepartment(
          int index, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment.Builder builderForValue) {
        if (departmentBuilder_ == null) {
          ensureDepartmentIsMutable();
          department_.set(index, builderForValue.build());
          onChanged();
        } else {
          departmentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addDepartment(net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment value) {
        if (departmentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDepartmentIsMutable();
          department_.add(value);
          onChanged();
        } else {
          departmentBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addDepartment(
          int index, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment value) {
        if (departmentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDepartmentIsMutable();
          department_.add(index, value);
          onChanged();
        } else {
          departmentBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addDepartment(
          net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment.Builder builderForValue) {
        if (departmentBuilder_ == null) {
          ensureDepartmentIsMutable();
          department_.add(builderForValue.build());
          onChanged();
        } else {
          departmentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addDepartment(
          int index, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment.Builder builderForValue) {
        if (departmentBuilder_ == null) {
          ensureDepartmentIsMutable();
          department_.add(index, builderForValue.build());
          onChanged();
        } else {
          departmentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllDepartment(
          java.lang.Iterable<? extends net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment> values) {
        if (departmentBuilder_ == null) {
          ensureDepartmentIsMutable();
          super.addAll(values, department_);
          onChanged();
        } else {
          departmentBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearDepartment() {
        if (departmentBuilder_ == null) {
          department_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          departmentBuilder_.clear();
        }
        return this;
      }
      public Builder removeDepartment(int index) {
        if (departmentBuilder_ == null) {
          ensureDepartmentIsMutable();
          department_.remove(index);
          onChanged();
        } else {
          departmentBuilder_.remove(index);
        }
        return this;
      }
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment.Builder getDepartmentBuilder(
          int index) {
        return getDepartmentFieldBuilder().getBuilder(index);
      }
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.DeptartmentOrBuilder getDepartmentOrBuilder(
          int index) {
        if (departmentBuilder_ == null) {
          return department_.get(index);  } else {
          return departmentBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.DeptartmentOrBuilder> 
           getDepartmentOrBuilderList() {
        if (departmentBuilder_ != null) {
          return departmentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(department_);
        }
      }
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment.Builder addDepartmentBuilder() {
        return getDepartmentFieldBuilder().addBuilder(
            net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment.getDefaultInstance());
      }
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment.Builder addDepartmentBuilder(
          int index) {
        return getDepartmentFieldBuilder().addBuilder(
            index, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment.getDefaultInstance());
      }
      public java.util.List<net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment.Builder> 
           getDepartmentBuilderList() {
        return getDepartmentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment.Builder, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.DeptartmentOrBuilder> 
          getDepartmentFieldBuilder() {
        if (departmentBuilder_ == null) {
          departmentBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment.Builder, net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.DeptartmentOrBuilder>(
                  department_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          department_ = null;
        }
        return departmentBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.Store)
    }
    
    static {
      defaultInstance = new Store(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.Store)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Product_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Product_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Deptartment_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Deptartment_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Store_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Store_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020StoreSales.proto\022+net.sf.RecordEditor." +
      "ProtoBuf.re.Test.Sales2\"M\n\007Product\022\017\n\007ke" +
      "ycode\030\001 \002(\005\022\020\n\010saleDate\030\002 \002(\005\022\020\n\010quantit" +
      "y\030\003 \002(\005\022\r\n\005price\030\004 \002(\003\"v\n\013Deptartment\022\022\n" +
      "\ndepartment\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\022E\n\007produ" +
      "ct\030\003 \003(\01324.net.sf.RecordEditor.ProtoBuf." +
      "re.Test.Sales2.Product\"r\n\005Store\022\r\n\005store" +
      "\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\022L\n\ndepartment\030\003 \003(\013" +
      "28.net.sf.RecordEditor.ProtoBuf.re.Test." +
      "Sales2.DeptartmentB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Product_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Product_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Product_descriptor,
              new java.lang.String[] { "Keycode", "SaleDate", "Quantity", "Price", },
              net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product.class,
              net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Product.Builder.class);
          internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Deptartment_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Deptartment_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Deptartment_descriptor,
              new java.lang.String[] { "Department", "Name", "Product", },
              net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment.class,
              net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Deptartment.Builder.class);
          internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Store_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Store_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales2_Store_descriptor,
              new java.lang.String[] { "Store", "Name", "Department", },
              net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store.class,
              net.sf.RecordEditor.ProtoBuf.re.Test.Sales2.StoreSales.Store.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
