// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StoreSales6SD_Department.proto

package net.sf.RecordEditor.ProtoBuf.re.Test.Sales3;

public final class StoreSales6SDDepartment {
  private StoreSales6SDDepartment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DeptartmentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 department = 1;
    boolean hasDepartment();
    int getDepartment();
    
    // required string name = 2;
    boolean hasName();
    String getName();
    
    // repeated .net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.Product product = 3;
    java.util.List<net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product> 
        getProductList();
    net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product getProduct(int index);
    int getProductCount();
    java.util.List<? extends net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.ProductOrBuilder> 
        getProductOrBuilderList();
    net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.ProductOrBuilder getProductOrBuilder(
        int index);
    
    // optional .net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.Summary summary = 4;
    boolean hasSummary();
    net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary getSummary();
    net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.SummaryOrBuilder getSummaryOrBuilder();
  }
  public static final class Deptartment extends
      com.google.protobuf.GeneratedMessage
      implements DeptartmentOrBuilder {
    // Use Deptartment.newBuilder() to construct.
    private Deptartment(Builder builder) {
      super(builder);
    }
    private Deptartment(boolean noInit) {}
    
    private static final Deptartment defaultInstance;
    public static Deptartment getDefaultInstance() {
      return defaultInstance;
    }
    
    public Deptartment getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales3_Deptartment_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales3_Deptartment_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 department = 1;
    public static final int DEPARTMENT_FIELD_NUMBER = 1;
    private int department_;
    public boolean hasDepartment() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getDepartment() {
      return department_;
    }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.Product product = 3;
    public static final int PRODUCT_FIELD_NUMBER = 3;
    private java.util.List<net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product> product_;
    public java.util.List<net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product> getProductList() {
      return product_;
    }
    public java.util.List<? extends net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.ProductOrBuilder> 
        getProductOrBuilderList() {
      return product_;
    }
    public int getProductCount() {
      return product_.size();
    }
    public net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product getProduct(int index) {
      return product_.get(index);
    }
    public net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.ProductOrBuilder getProductOrBuilder(
        int index) {
      return product_.get(index);
    }
    
    // optional .net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.Summary summary = 4;
    public static final int SUMMARY_FIELD_NUMBER = 4;
    private net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary summary_;
    public boolean hasSummary() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary getSummary() {
      return summary_;
    }
    public net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.SummaryOrBuilder getSummaryOrBuilder() {
      return summary_;
    }
    
    private void initFields() {
      department_ = 0;
      name_ = "";
      product_ = java.util.Collections.emptyList();
      summary_ = net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDepartment()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getProductCount(); i++) {
        if (!getProduct(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasSummary()) {
        if (!getSummary().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, department_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      for (int i = 0; i < product_.size(); i++) {
        output.writeMessage(3, product_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(4, summary_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, department_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      for (int i = 0; i < product_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, product_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, summary_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.DeptartmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales3_Deptartment_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales3_Deptartment_fieldAccessorTable;
      }
      
      // Construct using net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getProductFieldBuilder();
          getSummaryFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        department_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (productBuilder_ == null) {
          product_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          productBuilder_.clear();
        }
        if (summaryBuilder_ == null) {
          summary_ = net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary.getDefaultInstance();
        } else {
          summaryBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment.getDescriptor();
      }
      
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment getDefaultInstanceForType() {
        return net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment.getDefaultInstance();
      }
      
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment build() {
        net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment buildPartial() {
        net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment result = new net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.department_ = department_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (productBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            product_ = java.util.Collections.unmodifiableList(product_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.product_ = product_;
        } else {
          result.product_ = productBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        if (summaryBuilder_ == null) {
          result.summary_ = summary_;
        } else {
          result.summary_ = summaryBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment) {
          return mergeFrom((net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment other) {
        if (other == net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment.getDefaultInstance()) return this;
        if (other.hasDepartment()) {
          setDepartment(other.getDepartment());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (productBuilder_ == null) {
          if (!other.product_.isEmpty()) {
            if (product_.isEmpty()) {
              product_ = other.product_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureProductIsMutable();
              product_.addAll(other.product_);
            }
            onChanged();
          }
        } else {
          if (!other.product_.isEmpty()) {
            if (productBuilder_.isEmpty()) {
              productBuilder_.dispose();
              productBuilder_ = null;
              product_ = other.product_;
              bitField0_ = (bitField0_ & ~0x00000004);
              productBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getProductFieldBuilder() : null;
            } else {
              productBuilder_.addAllMessages(other.product_);
            }
          }
        }
        if (other.hasSummary()) {
          mergeSummary(other.getSummary());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDepartment()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        for (int i = 0; i < getProductCount(); i++) {
          if (!getProduct(i).isInitialized()) {
            
            return false;
          }
        }
        if (hasSummary()) {
          if (!getSummary().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              department_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product.Builder subBuilder = net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addProduct(subBuilder.buildPartial());
              break;
            }
            case 34: {
              net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary.Builder subBuilder = net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary.newBuilder();
              if (hasSummary()) {
                subBuilder.mergeFrom(getSummary());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSummary(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 department = 1;
      private int department_ ;
      public boolean hasDepartment() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getDepartment() {
        return department_;
      }
      public Builder setDepartment(int value) {
        bitField0_ |= 0x00000001;
        department_ = value;
        onChanged();
        return this;
      }
      public Builder clearDepartment() {
        bitField0_ = (bitField0_ & ~0x00000001);
        department_ = 0;
        onChanged();
        return this;
      }
      
      // required string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // repeated .net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.Product product = 3;
      private java.util.List<net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product> product_ =
        java.util.Collections.emptyList();
      private void ensureProductIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          product_ = new java.util.ArrayList<net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product>(product_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product, net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product.Builder, net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.ProductOrBuilder> productBuilder_;
      
      public java.util.List<net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product> getProductList() {
        if (productBuilder_ == null) {
          return java.util.Collections.unmodifiableList(product_);
        } else {
          return productBuilder_.getMessageList();
        }
      }
      public int getProductCount() {
        if (productBuilder_ == null) {
          return product_.size();
        } else {
          return productBuilder_.getCount();
        }
      }
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product getProduct(int index) {
        if (productBuilder_ == null) {
          return product_.get(index);
        } else {
          return productBuilder_.getMessage(index);
        }
      }
      public Builder setProduct(
          int index, net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product value) {
        if (productBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductIsMutable();
          product_.set(index, value);
          onChanged();
        } else {
          productBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setProduct(
          int index, net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product.Builder builderForValue) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.set(index, builderForValue.build());
          onChanged();
        } else {
          productBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addProduct(net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product value) {
        if (productBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductIsMutable();
          product_.add(value);
          onChanged();
        } else {
          productBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addProduct(
          int index, net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product value) {
        if (productBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductIsMutable();
          product_.add(index, value);
          onChanged();
        } else {
          productBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addProduct(
          net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product.Builder builderForValue) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.add(builderForValue.build());
          onChanged();
        } else {
          productBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addProduct(
          int index, net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product.Builder builderForValue) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.add(index, builderForValue.build());
          onChanged();
        } else {
          productBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllProduct(
          java.lang.Iterable<? extends net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product> values) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          super.addAll(values, product_);
          onChanged();
        } else {
          productBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearProduct() {
        if (productBuilder_ == null) {
          product_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          productBuilder_.clear();
        }
        return this;
      }
      public Builder removeProduct(int index) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.remove(index);
          onChanged();
        } else {
          productBuilder_.remove(index);
        }
        return this;
      }
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product.Builder getProductBuilder(
          int index) {
        return getProductFieldBuilder().getBuilder(index);
      }
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.ProductOrBuilder getProductOrBuilder(
          int index) {
        if (productBuilder_ == null) {
          return product_.get(index);  } else {
          return productBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.ProductOrBuilder> 
           getProductOrBuilderList() {
        if (productBuilder_ != null) {
          return productBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(product_);
        }
      }
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product.Builder addProductBuilder() {
        return getProductFieldBuilder().addBuilder(
            net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product.getDefaultInstance());
      }
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product.Builder addProductBuilder(
          int index) {
        return getProductFieldBuilder().addBuilder(
            index, net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product.getDefaultInstance());
      }
      public java.util.List<net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product.Builder> 
           getProductBuilderList() {
        return getProductFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product, net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product.Builder, net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.ProductOrBuilder> 
          getProductFieldBuilder() {
        if (productBuilder_ == null) {
          productBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product, net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.Product.Builder, net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.ProductOrBuilder>(
                  product_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          product_ = null;
        }
        return productBuilder_;
      }
      
      // optional .net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.Summary summary = 4;
      private net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary summary_ = net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary, net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary.Builder, net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.SummaryOrBuilder> summaryBuilder_;
      public boolean hasSummary() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary getSummary() {
        if (summaryBuilder_ == null) {
          return summary_;
        } else {
          return summaryBuilder_.getMessage();
        }
      }
      public Builder setSummary(net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary value) {
        if (summaryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          summary_ = value;
          onChanged();
        } else {
          summaryBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setSummary(
          net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary.Builder builderForValue) {
        if (summaryBuilder_ == null) {
          summary_ = builderForValue.build();
          onChanged();
        } else {
          summaryBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeSummary(net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary value) {
        if (summaryBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              summary_ != net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary.getDefaultInstance()) {
            summary_ =
              net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary.newBuilder(summary_).mergeFrom(value).buildPartial();
          } else {
            summary_ = value;
          }
          onChanged();
        } else {
          summaryBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearSummary() {
        if (summaryBuilder_ == null) {
          summary_ = net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary.getDefaultInstance();
          onChanged();
        } else {
          summaryBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary.Builder getSummaryBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getSummaryFieldBuilder().getBuilder();
      }
      public net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.SummaryOrBuilder getSummaryOrBuilder() {
        if (summaryBuilder_ != null) {
          return summaryBuilder_.getMessageOrBuilder();
        } else {
          return summary_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary, net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary.Builder, net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.SummaryOrBuilder> 
          getSummaryFieldBuilder() {
        if (summaryBuilder_ == null) {
          summaryBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary, net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.Summary.Builder, net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.SummaryOrBuilder>(
                  summary_,
                  getParentForChildren(),
                  isClean());
          summary_ = null;
        }
        return summaryBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.Deptartment)
    }
    
    static {
      defaultInstance = new Deptartment(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.Deptartment)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales3_Deptartment_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales3_Deptartment_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036StoreSales6SD_Department.proto\022+net.sf" +
      ".RecordEditor.ProtoBuf.re.Test.Sales3\032\033S" +
      "toreSales6SD_Product.proto\032\026StoreSales6S" +
      "D_MO.proto\"\275\001\n\013Deptartment\022\022\n\ndepartment" +
      "\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\022E\n\007product\030\003 \003(\01324." +
      "net.sf.RecordEditor.ProtoBuf.re.Test.Sal" +
      "es3.Product\022E\n\007summary\030\004 \001(\01324.net.sf.Re" +
      "cordEditor.ProtoBuf.re.Test.Sales3.Summa" +
      "ryB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales3_Deptartment_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales3_Deptartment_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_sf_RecordEditor_ProtoBuf_re_Test_Sales3_Deptartment_descriptor,
              new java.lang.String[] { "Department", "Name", "Product", "Summary", },
              net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment.class,
              net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDDepartment.Deptartment.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDProduct.getDescriptor(),
          net.sf.RecordEditor.ProtoBuf.re.Test.Sales3.StoreSales6SDMO.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
